package io.flutter.plugins

import flutter.curiosity.CuriosityPlugin
import io.flutter.embedding.engine.FlutterEngine

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
object GeneratedPluginRegistrant {
    fun registerWith(flutterEngine: FlutterEngine) {
        flutterEngine.plugins.add(CuriosityPlugin())
    }
}